// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvASHLGf8RXQXXqfT6dntn_B16Yh0vkyQ',
    appId: '1:160626796012:web:d78968ea501a85e7b90cc9',
    messagingSenderId: '160626796012',
    projectId: 'mental-health-app-65976',
    authDomain: 'mental-health-app-65976.firebaseapp.com',
    storageBucket: 'mental-health-app-65976.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw5Qa7o4Ug0YsLKcsVa9ETdtvkkfikbYI',
    appId: '1:160626796012:android:abac93e548cc4576b90cc9',
    messagingSenderId: '160626796012',
    projectId: 'mental-health-app-65976',
    storageBucket: 'mental-health-app-65976.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsHkXY7y6QLXSoShLvuWn3MH1UlZYBO5Q',
    appId: '1:160626796012:ios:f63ea9f25b94fc85b90cc9',
    messagingSenderId: '160626796012',
    projectId: 'mental-health-app-65976',
    storageBucket: 'mental-health-app-65976.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsHkXY7y6QLXSoShLvuWn3MH1UlZYBO5Q',
    appId: '1:160626796012:ios:f63ea9f25b94fc85b90cc9',
    messagingSenderId: '160626796012',
    projectId: 'mental-health-app-65976',
    storageBucket: 'mental-health-app-65976.firebasestorage.app',
    iosBundleId: 'com.example.mentalHealthApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvASHLGf8RXQXXqfT6dntn_B16Yh0vkyQ',
    appId: '1:160626796012:web:4d718c849259e723b90cc9',
    messagingSenderId: '160626796012',
    projectId: 'mental-health-app-65976',
    authDomain: 'mental-health-app-65976.firebaseapp.com',
    storageBucket: 'mental-health-app-65976.firebasestorage.app',
  );
}
